### ISSUE TITLE
New flight - changing dropdown menu choice don't update anything

### ISSUE THREAD

**Issue by x41lakazam** [hatalLab/rohash_maintenace#11]
Changing the value of the dropdown menu should modify the $(#coordinates) element (hidden selectfield) in this way:
1) Add the new `<option>`
2) Set this `<option>` as selected

**Comment by avi747av** [comment]
i don't sure i understand what you mean.
after every selection i remove the previous selection from the hidden select (id= selector)
and append the new selected value as the selected option (id=selected)

**Comment by x41lakazam** [comment]
This is the state of the code before changing anything:
https://pastebin.com/vuGGeRCC

This is the state of the code after selecting something:
https://pastebin.com/ib7b7dFg

The only change is here:
`<p id="selection">&nbsp;&nbsp; Ganei Tikva (N°32.06,E°34.87)</p>`

The form is not modified, this:
`<select hidden="hidden" id="coordinates" name="coordinates"><option value="Name:Rahat_N:31.39547_E:34.75699">Rahat (N°31.40,E°34.76)</option><option value="Name:Ramla_N:31.92923_E:34.86563">Ramla (N°31.93,E°34.87)</option><option value="Name:Ganei Tikva_N:32.05971_E:34.8732">Ganei Tikva (N°32.06,E°34.87)</option></select>`

should become this:
`<select hidden="hidden" id="coordinates" name="coordinates"><option value="Name:Rahat_N:31.39547_E:34.75699">Rahat (N°31.40,E°34.76)</option><option value="Name:Ramla_N:31.92923_E:34.86563">Ramla (N°31.93,E°34.87)</option><option selected value="Name:Ganei Tikva_N:32.05971_E:34.8732">Ganei Tikva (N°32.06,E°34.87)</option></select>`

Notice the `selected` attribute added to the last option.

If the form isn't changed I can't get the result in the server side..

Try to see [w3c reference on select field](https://www.w3schools.com/tags/att_option_selected.asp)

**Comment by x41lakazam** [comment]
resolved on #14
